=== olyop/go-warriors/jsonschema-generators/nba-api-games.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "get": {
      "type": "string"
    },
    "parameters": {
      "type": "object",
      "properties": {
        "date": {
          "type": "string"
        }
      }
    },
    "errors": {
      "type": "object",
      "properties": {}
    },
    "results": {
      "type": "number"
    },
    "response": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "league": {
            "type": "string"
          },
          "season": {
            "type": "number"
          },
          "date": {
            "type": "object",
            "properties": {
              "start": {
                "type": "string"
              },
              "end": {
                "type": "null"
              },
              "duration": {
                "type": "null"
              }
            }
          },
          "stage": {
            "type": "number"
          },
          "status": {
            "type": "object",
            "properties": {
              "clock": {
                "type": "null"
              },
              "halftime": {
                "type": "boolean"
              },
              "short": {
                "type": "number"
              },
              "long": {
                "type": "string"
              }
            }
          },
          "periods": {
            "type": "object",
            "properties": {
              "current": {
                "type": "number"
              },
              "total": {
                "type": "number"
              },
              "endOfPeriod": {
                "type": "boolean"
              }
            }
          },
          "arena": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "city": {
                "type": "string"
              },
              "state": {
                "type": "string"
              },
              "country": {
                "type": "null"
              }
            }
          },
          "teams": {
            "type": "object",
            "properties": {
              "visitors": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "number"
                  },
                  "name": {
                    "type": "string"
                  },
                  "nickname": {
                    "type": "string"
                  },
                  "code": {
                    "type": "string"
                  },
                  "logo": {
                    "type": "string"
                  }
                }
              },
              "home": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "number"
                  },
                  "name": {
                    "type": "string"
                  },
                  "nickname": {
                    "type": "string"
                  },
                  "code": {
                    "type": "string"
                  },
                  "logo": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "scores": {
            "type": "object",
            "properties": {
              "visitors": {
                "type": "object",
                "properties": {
                  "win": {
                    "type": "number"
                  },
                  "loss": {
                    "type": "number"
                  },
                  "series": {
                    "type": "object",
                    "properties": {
                      "win": {
                        "type": "number"
                      },
                      "loss": {
                        "type": "number"
                      }
                    }
                  },
                  "linescore": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "points": {
                    "type": "number"
                  }
                }
              },
              "home": {
                "type": "object",
                "properties": {
                  "win": {
                    "type": "number"
                  },
                  "loss": {
                    "type": "number"
                  },
                  "series": {
                    "type": "object",
                    "properties": {
                      "win": {
                        "type": "number"
                      },
                      "loss": {
                        "type": "number"
                      }
                    }
                  },
                  "linescore": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "points": {
                    "type": "number"
                  }
                }
              }
            }
          },
          "officials": {
            "type": "array",
            "items": {}
          },
          "timesTied": {
            "type": "null"
          },
          "leadChanges": {
            "type": "null"
          },
          "nugget": {
            "type": "null"
          }
        },
        "required": [
          "id",
          "league",
          "season",
          "date",
          "stage",
          "status",
          "periods",
          "arena",
          "teams",
          "scores",
          "officials",
          "timesTied",
          "leadChanges",
          "nugget"
        ]
      }
    }
  }
}

=== olyop/go-warriors/jsonschema-generators/nba-api-games-sample.json
{
    "get": "games/",
    "parameters": {
        "date": "2024-03-25"
    },
    "errors": {},
    "results": 5,
    "response": [
        {
            "id": 13580,
            "league": "standard",
            "season": 2023,
            "date": {
                "start": "2024-03-25T02:00:00.000Z",
                "end": null,
                "duration": null
            },
            "stage": 2,
            "status": {
                "clock": null,
                "halftime": false,
                "short": 3,
                "long": "Finished"
            },
            "periods": {
                "current": 4,
                "total": 4,
                "endOfPeriod": false
            },
            "arena": {
                "name": "crypto.com Arena",
                "city": "Los Angeles",
                "state": "CA",
                "country": null
            },
            "teams": {
                "visitors": {
                    "id": 15,
                    "name": "Indiana Pacers",
                    "nickname": "Pacers",
                    "code": "IND",
                    "logo": "https://upload.wikimedia.org/wikipedia/fr/thumb/c/cf/Pacers_de_l%27Indiana_logo.svg/1180px-Pacers_de_l%27Indiana_logo.svg.png"
                },
                "home": {
                    "id": 17,
                    "name": "Los Angeles Lakers",
                    "nickname": "Lakers",
                    "code": "LAL",
                    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Los_Angeles_Lakers_logo.svg/220px-Los_Angeles_Lakers_logo.svg.png"
                }
            },
            "scores": {
                "visitors": {
                    "win": 0,
                    "loss": 0,
                    "series": {
                        "win": 0,
                        "loss": 0
                    },
                    "linescore": [
                        "36",
                        "32",
                        "31",
                        "46"
                    ],
                    "points": 145
                },
                "home": {
                    "win": 0,
                    "loss": 0,
                    "series": {
                        "win": 0,
                        "loss": 0
                    },
                    "linescore": [
                        "30",
                        "42",
                        "44",
                        "34"
                    ],
                    "points": 150
                }
            },
            "officials": [],
            "timesTied": null,
            "leadChanges": null,
            "nugget": null
        },
        {
            "id": 13581,
            "league": "standard",
            "season": 2023,
            "date": {
                "start": "2024-03-25T23:00:00.000Z",
                "end": null,
                "duration": null
            },
            "stage": 2,
            "status": {
                "clock": null,
                "halftime": false,
                "short": 3,
                "long": "Finished"
            },
            "periods": {
                "current": 4,
                "total": 4,
                "endOfPeriod": false
            },
            "arena": {
                "name": "Rocket Mortgage FieldHouse",
                "city": "Cleveland",
                "state": "OH",
                "country": null
            },
            "teams": {
                "visitors": {
                    "id": 5,
                    "name": "Charlotte Hornets",
                    "nickname": "Hornets",
                    "code": "CHA",
                    "logo": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f3/Hornets_de_Charlotte_logo.svg/1200px-Hornets_de_Charlotte_logo.svg.png"
                },
                "home": {
                    "id": 7,
                    "name": "Cleveland Cavaliers",
                    "nickname": "Cavaliers",
                    "code": "CLE",
                    "logo": "https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png"
                }
            },
            "scores": {
                "visitors": {
                    "win": 0,
                    "loss": 0,
                    "series": {
                        "win": 0,
                        "loss": 0
                    },
                    "linescore": [
                        "20",
                        "17",
                        "29",
                        "26"
                    ],
                    "points": 92
                },
                "home": {
                    "win": 0,
                    "loss": 0,
                    "series": {
                        "win": 0,
                        "loss": 0
                    },
                    "linescore": [
                        "20",
                        "31",
                        "27",
                        "37"
                    ],
                    "points": 115
                }
            },
            "officials": [],
            "timesTied": null,
            "leadChanges": null,
            "nugget": null
        },
        {
            "id": 13582,
            "league": "standard",
            "season": 2023,
            "date": {
                "start": "2024-03-25T23:30:00.000Z",
                "end": null,
                "duration": null
            },
            "stage": 2,
            "status": {
                "clock": null,
                "halftime": false,
                "short": 3,
                "long": "Finished"
            },
            "periods": {
                "current": 4,
                "total": 4,
                "endOfPeriod": false
            },
            "arena": {
                "name": "State Farm Arena",
                "city": "Atlanta",
                "state": "GA",
                "country": null
            },
            "teams": {
                "visitors": {
                    "id": 2,
                    "name": "Boston Celtics",
                    "nickname": "Celtics",
                    "code": "BOS",
                    "logo": "https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png"
                },
                "home": {
                    "id": 1,
                    "name": "Atlanta Hawks",
                    "nickname": "Hawks",
                    "code": "ATL",
                    "logo": "https://upload.wikimedia.org/wikipedia/fr/e/ee/Hawks_2016.png"
                }
            },
            "scores": {
                "visitors": {
                    "win": 0,
                    "loss": 0,
                    "series": {
                        "win": 0,
                        "loss": 0
                    },
                    "linescore": [
                        "44",
                        "30",
                        "22",
                        "22"
                    ],
                    "points": 118
                },
                "home": {
                    "win": 0,
                    "loss": 0,
                    "series": {
                        "win": 0,
                        "loss": 0
                    },
                    "linescore": [
                        "22",
                        "34",
                        "34",
                        "30"
                    ],
                    "points": 120
                }
            },
            "officials": [],
            "timesTied": null,
            "leadChanges": null,
            "nugget": null
        },
        {
            "id": 13583,
            "league": "standard",
            "season": 2023,
            "date": {
                "start": "2024-03-25T23:30:00.000Z",
                "end": null,
                "duration": null
            },
            "stage": 2,
            "status": {
                "clock": null,
                "halftime": false,
                "short": 3,
                "long": "Finished"
            },
            "periods": {
                "current": 4,
                "total": 4,
                "endOfPeriod": false
            },
            "arena": {
                "name": "Madison Square Garden",
                "city": "New York",
                "state": "NY",
                "country": null
            },
            "teams": {
                "visitors": {
                    "id": 10,
                    "name": "Detroit Pistons",
                    "nickname": "Pistons",
                    "code": "DET",
                    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Logo_of_the_Detroit_Pistons.png/300px-Logo_of_the_Detroit_Pistons.png"
                },
                "home": {
                    "id": 24,
                    "name": "New York Knicks",
                    "nickname": "Knicks",
                    "code": "NYK",
                    "logo": "https://upload.wikimedia.org/wikipedia/fr/3/34/Knicks_de_NY.png"
                }
            },
            "scores": {
                "visitors": {
                    "win": 0,
                    "loss": 0,
                    "series": {
                        "win": 0,
                        "loss": 0
                    },
                    "linescore": [
                        "17",
                        "25",
                        "24",
                        "33"
                    ],
                    "points": 99
                },
                "home": {
                    "win": 0,
                    "loss": 0,
                    "series": {
                        "win": 0,
                        "loss": 0
                    },
                    "linescore": [
                        "36",
                        "23",
